[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://ton-jacket.netlify.app"

[functions."create-invoice"]
  origin = "https://ton-jacket.netlify.app"

[functions."verify-payment"]
  origin = "https://ton-jacket.netlify.app"

[functions."updateWallet"]
  origin = "https://ton-jacket.netlify.app"

[functions."update-coins.js"]
  origin = "https://ton-jacket.netlify.app" 

[functions."update-bet.js"]
  origin = "https://ton-jacket.netlify.app" 

[functions."update-ton"]
  origin = "https://ton-jacket.netlify.app" 
  
[functions."convertCoinsToTON.js"]
  origin = "https://ton-jacket.netlify.app"

[functions."deposit-ton.js"]
  origin = "https://ton-jacket.netlify.app"  

[functions."process-withdraw.js"]
  origin = "https://ton-jacket.netlify.app"     